version: "3"
services:
#  gluetun:
#    image: qmcgaw/gluetun
#    cap_add:
#      - NET_ADMIN
#    environment:
      # configure your vpn credentials accordig to https://github.com/qdm12/gluetun/wiki
#      VPNSP: <provider>
#      OPENVPN_USER: <user>
#      OPENVPN_PASSWORD: <password>
#      REGION: <region>
  bombardier:
    build: .
    image: bombardier
    container_name: bombardier
    #network_mode: "service:gluetun"
    restart: always
    environment:
      CONNECTIONS: 30
      INTERVAL: 10m
      RESOURCES_URL: https://raw.githubusercontent.com/almerico/bombardier/main/resources_all.txt